    replicaCount: 2

    image: 
      repository: 602401143452.dkr.ecr.${aws_region}.amazonaws.com/amazon/aws-load-balancer-controller
      tag: ${version_alb}
      pullPolicy: IfNotPresent
     
    serviceAccount: 
      create: true
      annotations:
        eks.amazonaws.com/role-arn: ${aws_arn_alb}

    clusterName: ${cluster_name}
    region: ${aws_region}
    

